### PR TITLE
Update asc_editor.py

### PR DESCRIPTION
**Pull request by marmeladapk**
Ignore rectangles in ASC files

### CODE REVIEW

**Comment by hb020** [comment]
It might be better if we have proper support for rectangles. The "asy editor" has it, so it should be possible to add it. Will take a look.

**Comment by marmeladapk** [comment]
Sorry, might be a bit ignorant here, what do you mean by "proper support for rectangles"? So that you can preserve them in rewritten asc?

**Comment by hb020** [comment]
indeed, still looking how to do it. We might start with ignoring it short term, and in the next release go for preserving it.

**Comment by hb020** [comment]
Preservation of all types of graphical elements is now possible. 
See branch "asceditor-encoding-fix-https://github.com/nunobrum/spicelib/issues/45" on top of branch v1.1.3.
Will close this when the branch is merged back into main.

**Review by nunobrum — APPROVED** [review]

**Comment by nunobrum** [comment]
I agree with @hb020 a proper handling would be better. 
This is something that we can add later. In the meantime, since it's causing the script to raise an exception, we can ignore it.

**Pull request merged**
