### PR TITLE
move modified_subcircuits up

### PR DESCRIPTION
**Pull request by hb020**

### CODE REVIEW

**Comment by nunobrum** [comment]
Yes! This goes in the right direction. However, I will further develop this and move the rest of the management to the SpiceCircuit. As of today, the implementation has a nasty limitation. It only allows to have one level of sub-circuit redirection. Moving everything to the SpiceCircuit, would allow to access sub-circuits inside of sub-circuits, inside of sub-circuits.... like a Matrioshka.

**Comment by hb020** [comment]
understood. Would be better indeed.

**Comment by nunobrum** [comment]
It seems to be working. Need still to include a testbench with two levels of subcircuit to fully test it.

**Comment by nunobrum** [comment]
Here it is. It is a working code that can manage the update of sub-circuits inside sub-circuits.
Unfortunately, this doesn't work with : 
`netlist["X1:X2:R1"].value = new_value`
The form 
`netlist.set_component_value("X1:X2:R1", new_value)`

The reason is that the first form finds the resistor inside the sub-circuit and then sets it on the last sub-circuit found.
There are a few workarounds for this, but, I'll implement it later.

**Comment by hb020** [comment]
can you make the changes also work in asceditor? If not, please move the first line you modified:
```
- self.assertEqual(my_edt.get_subcircuit(sc).get_components(), ['C1', 'C2', 'L1'], "Subcircuit component list")
+ self.assertEqual(my_edt.get_subcircuit(sc).get_components(), ['C1', 'X2', 'L1'], "Subcircuit component list")
```
outside of the "identical part" section, in both files. A copy/paste risks killing the test set otherwise.

About 

> Unfortunately, this doesn't work with : 
> `netlist["X1:X2:R1"].value = new_value` 
> The form 
> `netlist.set_component_value("X1:X2:R1", new_value)`

That's indeed a shame. One would think that both parser are the same. But if it's complicated to do, nothing a bit of explanation in readme and help about limitations can't solve.

**Comment by nunobrum** [comment]
>can you make the changes also work in asceditor? If not, please move the first line you modified:

Not sure what you mean. You prefer that I create a completely new testbench ?

Regarding the limitation above, I was thinking about having an helper intermediate class, that is returned by the __getitem__ that keeps the original parent and reference.
It's kind of a hack, but I think it solves the issue.

**Comment by nunobrum** [comment]
Everything now working as expected. Moved the assertion with `get_subcircuit(sc).get_components()` outside the identical part

**Pull request merged**
