### PR TITLE
Allow MOS parameters #109

### PR DESCRIPTION
**Pull request by hb020**
See #109 

also did a pass on the documentation

### CODE REVIEW

**Comment by hb020** [comment]
Don't merge yet, as the protection against setting parameters on components from libs might be incomplete. Will test that.

**Comment by nunobrum** [comment]
I am anyway refactoring that part. The actual implementation doesn't allow to set parameters in subcircuits.
Will make a push very soon.

**Review by nunobrum — APPROVED** [review]

**Comment by nunobrum** [comment]
What do you mean? They both accept the same types.
`def set_component_value(self, reference: str, value: Union[str, int, float]) -> None:`
and 
```    @value_str.setter
    def value_str(self, value: Union[str, int, float]):
```

**Comment by hb020** [comment]
The thing is that:
* Component.set_params calls `parent.set_component_parameters()`
* Component.model setter calls `parent.set_element_model()`
* Component.value_str setter calls `parent.set_component_value()`

See the pattern?
but Component.value setter calls 
```python
        if self.parent.is_read_only():
            raise ValueError("Editor is read-only")
        if isinstance(value, (int, float)):
            self.value_str = format_eng(value)
        else:
            self.value_str = value
```
NOT the parent.

**Comment by nunobrum** [comment]
Because the magic actually happens on the value_str setter

```
    @value_str.setter
    def value_str(self, value: Union[str, int, float]):
        # docstring inherited from Component
        if self.parent.is_read_only():
            raise ValueError("Editor is read-only")        
        self.parent.set_component_value(self.reference, value)
```

If you don't have any other remarks, I'll proceed with the pull-request merge

**Comment by hb020** [comment]
indeed. it would be slightly more readable if parent.set_component_value() was called directly, but yes, this is all OK.

**Comment by nunobrum** [comment]
Dammed hurries! I've just realized that the edits I did on the README.md were on the wrong place. It was supposed to be on the SpiceEditor related  and ended up being on the AscEditor example.

**Pull request merged**
